In [1]:
import os

print(os.path.exists(r"D:\project\MindSense\Early_Detection\data\raw"))

True

In [2]:
import os

print(os.listdir(r"D:\project\MindSense\Early_Detection\data\raw"))

['student_data.csv.csv']

In [3]:
import pandas as pd

df = pd.read_csv(r"D:\project\MindSense\Early_Detection\data\raw\student_data.csv.csv")

df.head()

,StudentID,Profile,Timestamp,Heart_Rate,Blood_Pressure_Systolic,Blood_Pressure_Diastolic,Respiration_Rate,Sleep_Duration,Activity_Levels,Mood,Cognitive_Load,Study_Hours,Academic_Stressors,Stress_Level,Mental_Health_Status
0,1,High_Achiever,1/1/2015,74.9,116.9,74.2,15.4,7.24,7019,Neutral,6,4.8,0,Medium,Normal
1,1,High_Achiever,1/2/2015,69.8,120.2,74,14.7,6.16,5411,Sad,5,6.59,0,Medium,Mild Stress
2,1,High_Achiever,1/3/2015,69.5,113.7,75.3,15.6,7.33,5627,Happy,5,4.67,1,Medium,Depression
3,1,High_Achiever,1/4/2015,70.8,114.6,79.4,15.2,7.22,5051,Happy,6,6.19,0,Medium,Depression
4,1,High_Achiever,1/5/2015,70.2,117.1,75.5,15.2,7.1,8066,Neutral,5,5.76,2,Medium,Depression

In [4]:
df.shape

(38651, 15)

In [5]:
df.columns

Index(['StudentID', 'Profile', 'Timestamp', 'Heart_Rate',
       'Blood_Pressure_Systolic', 'Blood_Pressure_Diastolic',
       'Respiration_Rate', 'Sleep_Duration', 'Activity_Levels', 'Mood',
       'Cognitive_Load', 'Study_Hours', 'Academic_Stressors', 'Stress_Level',
       'Mental_Health_Status'],
      dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 38651 entries, 0 to 38650
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   StudentID                 38651 non-null  str
 1   Profile                   38651 non-null  str
 2   Timestamp                 38651 non-null  str
 3   Heart_Rate                38651 non-null  str
 4   Blood_Pressure_Systolic   38651 non-null  str
 5   Blood_Pressure_Diastolic  38651 non-null  str
 6   Respiration_Rate          38651 non-null  str
 7   Sleep_Duration            38651 non-null  str
 8   Activity_Levels           38651 non-null  str
 9   Mood                      38651 non-null  str
 10  Cognitive_Load            38651 non-null  str
 11  Study_Hours               38651 non-null  str
 12  Academic_Stressors        38651 non-null  str
 13  Stress_Level              38651 non-null  str
 14  Mental_Health_Status      38651 non-null  str
dtypes: str(15)
memory usage: 4.4 MB

In [7]:
import pandas as pd

df = pd.read_csv(r"D:\project\MindSense\Early_Detection\data\raw\student_data.csv.csv")

# Convert numeric columns
num_cols = [
    "Heart_Rate",
    "Blood_Pressure_Systolic",
    "Blood_Pressure_Diastolic",
    "Respiration_Rate",
    "Sleep_Duration",
    "Activity_Levels",
    "Cognitive_Load",
    "Study_Hours",
    "Academic_Stressors",
    "Stress_Level"
]

for col in num_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df.head()

,StudentID,Profile,Timestamp,Heart_Rate,Blood_Pressure_Systolic,Blood_Pressure_Diastolic,Respiration_Rate,Sleep_Duration,Activity_Levels,Mood,Cognitive_Load,Study_Hours,Academic_Stressors,Stress_Level,Mental_Health_Status
0,1,High_Achiever,1/1/2015,74.9,116.9,74.2,15.4,7.24,7019.0,Neutral,6.0,4.80,0.0,NaN,Normal
1,1,High_Achiever,1/2/2015,69.8,120.2,74.0,14.7,6.16,5411.0,Sad,5.0,6.59,0.0,NaN,Mild Stress
2,1,High_Achiever,1/3/2015,69.5,113.7,75.3,15.6,7.33,5627.0,Happy,5.0,4.67,1.0,NaN,Depression
3,1,High_Achiever,1/4/2015,70.8,114.6,79.4,15.2,7.22,5051.0,Happy,6.0,6.19,0.0,NaN,Depression
4,1,High_Achiever,1/5/2015,70.2,117.1,75.5,15.2,7.10,8066.0,Neutral,5.0,5.76,2.0,NaN,Depression

In [8]:
df["Timestamp"] = pd.to_datetime(df["Timestamp"], errors='coerce')

In [9]:
df.isnull().sum()

StudentID                       0
Profile                         0
Timestamp                       1
Heart_Rate                      1
Blood_Pressure_Systolic         1
Blood_Pressure_Diastolic        1
Respiration_Rate                1
Sleep_Duration                  1
Activity_Levels                 1
Mood                            0
Cognitive_Load                  1
Study_Hours                     1
Academic_Stressors              1
Stress_Level                38651
Mental_Health_Status            0
dtype: int64

In [10]:
df = df.dropna()

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 0 entries
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   StudentID                 0 non-null      str
 1   Profile                   0 non-null      str
 2   Timestamp                 0 non-null      datetime64[us]
 3   Heart_Rate                0 non-null      float64
 4   Blood_Pressure_Systolic   0 non-null      float64
 5   Blood_Pressure_Diastolic  0 non-null      float64
 6   Respiration_Rate          0 non-null      float64
 7   Sleep_Duration            0 non-null      float64
 8   Activity_Levels           0 non-null      float64
 9   Mood                      0 non-null      str
 10  Cognitive_Load            0 non-null      float64
 11  Study_Hours               0 non-null      float64
 12  Academic_Stressors        0 non-null      float64
 13  Stress_Level              0 non-null      float64
 14  Mental_Health_Status      0 non-null      str
dtypes: datetime64[us](1), float64(10), str(4)
memory usage: 132.0 bytes

In [12]:
import pandas as pd

df = pd.read_csv(r"D:\project\MindSense\Early_Detection\data\raw\student_data.csv.csv", encoding="utf-8")
print(df.shape)

(38651, 15)

In [13]:
with open(r"D:\project\MindSense\Early_Detection\data\raw\student_data.csv.csv", "r", encoding="utf-8") as f:
    for i in range(10):
        print(f.readline())

StudentID,Profile,Timestamp,Heart_Rate,Blood_Pressure_Systolic,Blood_Pressure_Diastolic,Respiration_Rate,Sleep_Duration,Activity_Levels,Mood,Cognitive_Load,Study_Hours,Academic_Stressors,Stress_Level,Mental_Health_Status

1,High_Achiever,1/1/2015,74.9,116.9,74.2,15.4,7.24,7019,Neutral,6,4.8,0,Medium,Normal

1,High_Achiever,1/2/2015,69.8,120.2,74,14.7,6.16,5411,Sad,5,6.59,0,Medium,Mild Stress

1,High_Achiever,1/3/2015,69.5,113.7,75.3,15.6,7.33,5627,Happy,5,4.67,1,Medium,Depression

1,High_Achiever,1/4/2015,70.8,114.6,79.4,15.2,7.22,5051,Happy,6,6.19,0,Medium,Depression

1,High_Achiever,1/5/2015,70.2,117.1,75.5,15.2,7.1,8066,Neutral,5,5.76,2,Medium,Depression

1,High_Achiever,1/6/2015,70.7,114,74.7,14.8,6.72,6450,Sad,6,4.61,1,Medium,Depression

1,High_Achiever,1/7/2015,69.7,117.4,77.6,15.7,6.14,6219,Anxious,5,4.86,0,Low,Depression

1,High_Achiever,1/8/2015,71.3,122,74.3,16.1,6.66,6822,Sad,6,5.49,0,Medium,Depression

1,High_Achiever,1/9/2015,70.6,122.3,77.4,16.4,6.57,5559,Sad,5,4.31,1,Medium,Depression

In [14]:
print(df.shape)

(38651, 15)

In [15]:
with open(r"D:\project\MindSense\Early_Detection\data\raw\student_data.csv.csv", "r", encoding="utf-8") as f:
    for i in range(10):
        print(f.readline())

StudentID,Profile,Timestamp,Heart_Rate,Blood_Pressure_Systolic,Blood_Pressure_Diastolic,Respiration_Rate,Sleep_Duration,Activity_Levels,Mood,Cognitive_Load,Study_Hours,Academic_Stressors,Stress_Level,Mental_Health_Status

1,High_Achiever,1/1/2015,74.9,116.9,74.2,15.4,7.24,7019,Neutral,6,4.8,0,Medium,Normal

1,High_Achiever,1/2/2015,69.8,120.2,74,14.7,6.16,5411,Sad,5,6.59,0,Medium,Mild Stress

1,High_Achiever,1/3/2015,69.5,113.7,75.3,15.6,7.33,5627,Happy,5,4.67,1,Medium,Depression

1,High_Achiever,1/4/2015,70.8,114.6,79.4,15.2,7.22,5051,Happy,6,6.19,0,Medium,Depression

1,High_Achiever,1/5/2015,70.2,117.1,75.5,15.2,7.1,8066,Neutral,5,5.76,2,Medium,Depression

1,High_Achiever,1/6/2015,70.7,114,74.7,14.8,6.72,6450,Sad,6,4.61,1,Medium,Depression

1,High_Achiever,1/7/2015,69.7,117.4,77.6,15.7,6.14,6219,Anxious,5,4.86,0,Low,Depression

1,High_Achiever,1/8/2015,71.3,122,74.3,16.1,6.66,6822,Sad,6,5.49,0,Medium,Depression

1,High_Achiever,1/9/2015,70.6,122.3,77.4,16.4,6.57,5559,Sad,5,4.31,1,Medium,Depression

In [16]:
df["Timestamp"].head(20)

0      1/1/2015
1      1/2/2015
2      1/3/2015
3      1/4/2015
4      1/5/2015
5      1/6/2015
6      1/7/2015
7      1/8/2015
8      1/9/2015
9     1/10/2015
10    1/11/2015
11    1/12/2015
12    1/13/2015
13    1/14/2015
14    1/15/2015
15    1/16/2015
16    1/17/2015
17    1/18/2015
18    1/19/2015
19    1/20/2015
Name: Timestamp, dtype: str

In [17]:
df["Timestamp"].unique()[:20]

<StringArray>
[ '1/1/2015',  '1/2/2015',  '1/3/2015',  '1/4/2015',  '1/5/2015',  '1/6/2015',
  '1/7/2015',  '1/8/2015',  '1/9/2015', '1/10/2015', '1/11/2015', '1/12/2015',
 '1/13/2015', '1/14/2015', '1/15/2015', '1/16/2015', '1/17/2015', '1/18/2015',
 '1/19/2015', '1/20/2015']
Length: 20, dtype: str

In [18]:
df["Timestamp"] = pd.to_datetime(df["Timestamp"], errors="coerce")

In [19]:
df["Timestamp"].isna().sum()

np.int64(1)

In [20]:
df = df.dropna(subset=["Timestamp"])

In [21]:
df = df.sort_values(by=["StudentID", "Timestamp"])

In [22]:
df = df.reset_index(drop=True)

In [23]:
df.head()

,StudentID,Profile,Timestamp,Heart_Rate,Blood_Pressure_Systolic,Blood_Pressure_Diastolic,Respiration_Rate,Sleep_Duration,Activity_Levels,Mood,Cognitive_Load,Study_Hours,Academic_Stressors,Stress_Level,Mental_Health_Status
0,1,High_Achiever,2015-01-01,74.9,116.9,74.2,15.4,7.24,7019,Neutral,6,4.8,0,Medium,Normal
1,1,High_Achiever,2015-01-02,69.8,120.2,74,14.7,6.16,5411,Sad,5,6.59,0,Medium,Mild Stress
2,1,High_Achiever,2015-01-03,69.5,113.7,75.3,15.6,7.33,5627,Happy,5,4.67,1,Medium,Depression
3,1,High_Achiever,2015-01-04,70.8,114.6,79.4,15.2,7.22,5051,Happy,6,6.19,0,Medium,Depression
4,1,High_Achiever,2015-01-05,70.2,117.1,75.5,15.2,7.1,8066,Neutral,5,5.76,2,Medium,Depression

In [24]:
df["Timestamp"] = pd.to_datetime(df["Timestamp"])
df = df.sort_values(["StudentID", "Timestamp"])
df.head()

,StudentID,Profile,Timestamp,Heart_Rate,Blood_Pressure_Systolic,Blood_Pressure_Diastolic,Respiration_Rate,Sleep_Duration,Activity_Levels,Mood,Cognitive_Load,Study_Hours,Academic_Stressors,Stress_Level,Mental_Health_Status
0,1,High_Achiever,2015-01-01,74.9,116.9,74.2,15.4,7.24,7019,Neutral,6,4.8,0,Medium,Normal
1,1,High_Achiever,2015-01-02,69.8,120.2,74,14.7,6.16,5411,Sad,5,6.59,0,Medium,Mild Stress
2,1,High_Achiever,2015-01-03,69.5,113.7,75.3,15.6,7.33,5627,Happy,5,4.67,1,Medium,Depression
3,1,High_Achiever,2015-01-04,70.8,114.6,79.4,15.2,7.22,5051,Happy,6,6.19,0,Medium,Depression
4,1,High_Achiever,2015-01-05,70.2,117.1,75.5,15.2,7.1,8066,Neutral,5,5.76,2,Medium,Depression

In [25]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df["Mental_Health_Status_encoded"] = le.fit_transform(df["Mental_Health_Status"])

df[["Mental_Health_Status", "Mental_Health_Status_encoded"]].head()

  Mental_Health_Status  Mental_Health_Status_encoded
0               Normal                             4
1          Mild Stress                             2
2           Depression                             1
3           Depression                             1
4           Depression                             1

In [26]:
df["Mood"] = LabelEncoder().fit_transform(df["Mood"])

In [27]:
df.head()

,StudentID,Profile,Timestamp,Heart_Rate,Blood_Pressure_Systolic,Blood_Pressure_Diastolic,Respiration_Rate,Sleep_Duration,Activity_Levels,Mood,Cognitive_Load,Study_Hours,Academic_Stressors,Stress_Level,Mental_Health_Status,Mental_Health_Status_encoded
0,1,High_Achiever,2015-01-01,74.9,116.9,74.2,15.4,7.24,7019,2,6,4.8,0,Medium,Normal,4
1,1,High_Achiever,2015-01-02,69.8,120.2,74,14.7,6.16,5411,3,5,6.59,0,Medium,Mild Stress,2
2,1,High_Achiever,2015-01-03,69.5,113.7,75.3,15.6,7.33,5627,1,5,4.67,1,Medium,Depression,1
3,1,High_Achiever,2015-01-04,70.8,114.6,79.4,15.2,7.22,5051,1,6,6.19,0,Medium,Depression,1
4,1,High_Achiever,2015-01-05,70.2,117.1,75.5,15.2,7.1,8066,2,5,5.76,2,Medium,Depression,1

In [28]:
df["Stress_Level"].value_counts()

Stress_Level
High      20095
Medium    18421
Low         134
Name: count, dtype: int64

In [29]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["Stress_Level_encoded"] = le.fit_transform(df["Stress_Level"])

df[["Stress_Level", "Stress_Level_encoded"]].head()

  Stress_Level  Stress_Level_encoded
0       Medium                     2
1       Medium                     2
2       Medium                     2
3       Medium                     2
4       Medium                     2

In [30]:
df["Timestamp"] = pd.to_datetime(df["Timestamp"])
df = df.sort_values(by=["StudentID", "Timestamp"])

In [31]:
df["StudentID"].nunique()

10

In [32]:
features = [
    "Heart_Rate",
    "Blood_Pressure_Systolic",
    "Blood_Pressure_Diastolic",
    "Respiration_Rate",
    "Sleep_Duration",
    "Activity_Levels",
    "Mood",
    "Cognitive_Load",
    "Study_Hours",
    "Academic_Stressors"
]

target = "Stress_Level_encoded"

In [33]:
data = df[features + [target]]
data.head()

,Heart_Rate,Blood_Pressure_Systolic,Blood_Pressure_Diastolic,Respiration_Rate,Sleep_Duration,Activity_Levels,Mood,Cognitive_Load,Study_Hours,Academic_Stressors,Stress_Level_encoded
0,74.9,116.9,74.2,15.4,7.24,7019,2,6,4.8,0,2
1,69.8,120.2,74,14.7,6.16,5411,3,5,6.59,0,2
2,69.5,113.7,75.3,15.6,7.33,5627,1,5,4.67,1,2
3,70.8,114.6,79.4,15.2,7.22,5051,1,6,6.19,0,2
4,70.2,117.1,75.5,15.2,7.1,8066,2,5,5.76,2,2

In [34]:
df.shape

(38650, 17)

In [35]:
df.columns

Index(['StudentID', 'Profile', 'Timestamp', 'Heart_Rate',
       'Blood_Pressure_Systolic', 'Blood_Pressure_Diastolic',
       'Respiration_Rate', 'Sleep_Duration', 'Activity_Levels', 'Mood',
       'Cognitive_Load', 'Study_Hours', 'Academic_Stressors', 'Stress_Level',
       'Mental_Health_Status', 'Mental_Health_Status_encoded',
       'Stress_Level_encoded'],
      dtype='str')

In [36]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 38650 entries, 0 to 38649
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   StudentID                     38650 non-null  str
 1   Profile                       38650 non-null  str
 2   Timestamp                     38650 non-null  datetime64[us]
 3   Heart_Rate                    38650 non-null  str
 4   Blood_Pressure_Systolic       38650 non-null  str
 5   Blood_Pressure_Diastolic      38650 non-null  str
 6   Respiration_Rate              38650 non-null  str
 7   Sleep_Duration                38650 non-null  str
 8   Activity_Levels               38650 non-null  str
 9   Mood                          38650 non-null  int64
 10  Cognitive_Load                38650 non-null  str
 11  Study_Hours                   38650 non-null  str
 12  Academic_Stressors            38650 non-null  str
 13  Stress_Level                  38650 non-null  str
 14  Mental_Health_Status          38650 non-null  str
 15  Mental_Health_Status_encoded  38650 non-null  int64
 16  Stress_Level_encoded          38650 non-null  int64
dtypes: datetime64[us](1), int64(3), str(13)
memory usage: 5.0 MB

In [37]:
df.isnull().sum()

StudentID                       0
Profile                         0
Timestamp                       0
Heart_Rate                      0
Blood_Pressure_Systolic         0
Blood_Pressure_Diastolic        0
Respiration_Rate                0
Sleep_Duration                  0
Activity_Levels                 0
Mood                            0
Cognitive_Load                  0
Study_Hours                     0
Academic_Stressors              0
Stress_Level                    0
Mental_Health_Status            0
Mental_Health_Status_encoded    0
Stress_Level_encoded            0
dtype: int64

In [38]:
df.duplicated().sum()

np.int64(0)

In [39]:
df.head(10)

,StudentID,Profile,Timestamp,Heart_Rate,Blood_Pressure_Systolic,Blood_Pressure_Diastolic,Respiration_Rate,Sleep_Duration,Activity_Levels,Mood,Cognitive_Load,Study_Hours,Academic_Stressors,Stress_Level,Mental_Health_Status,Mental_Health_Status_encoded,Stress_Level_encoded
0,1,High_Achiever,2015-01-01,74.9,116.9,74.2,15.4,7.24,7019,2,6,4.8,0,Medium,Normal,4,2
1,1,High_Achiever,2015-01-02,69.8,120.2,74,14.7,6.16,5411,3,5,6.59,0,Medium,Mild Stress,2,2
2,1,High_Achiever,2015-01-03,69.5,113.7,75.3,15.6,7.33,5627,1,5,4.67,1,Medium,Depression,1,2
3,1,High_Achiever,2015-01-04,70.8,114.6,79.4,15.2,7.22,5051,1,6,6.19,0,Medium,Depression,1,2
4,1,High_Achiever,2015-01-05,70.2,117.1,75.5,15.2,7.1,8066,2,5,5.76,2,Medium,Depression,1,2
5,1,High_Achiever,2015-01-06,70.7,114,74.7,14.8,6.72,6450,3,6,4.61,1,Medium,Depression,1,2
6,1,High_Achiever,2015-01-07,69.7,117.4,77.6,15.7,6.14,6219,0,5,4.86,0,Low,Depression,1,1
7,1,High_Achiever,2015-01-08,71.3,122,74.3,16.1,6.66,6822,3,6,5.49,0,Medium,Depression,1,2
8,1,High_Achiever,2015-01-09,70.6,122.3,77.4,16.4,6.57,5559,3,5,4.31,1,Medium,Depression,1,2
9,1,High_Achiever,2015-01-10,73.2,115.6,82,15.8,7.31,6774,1,6,5.48,1,Medium,Depression,1,2

In [40]:
df.describe()

,Timestamp,Mood,Mental_Health_Status_encoded,Stress_Level_encoded
count,38650,38650.000000,38650.000000,38650.000000
mean,2020-04-16 00:00:00,1.477335,1.865744,0.956688
min,2015-01-01 00:00:00,0.000000,0.000000,0.000000
25%,2017-08-24 00:00:00,0.000000,0.000000,0.000000
50%,2020-04-16 00:00:00,2.000000,1.000000,0.000000
75%,2022-12-08 00:00:00,3.000000,3.000000,2.000000
max,2025-07-31 00:00:00,3.000000,5.000000,2.000000
std,NaN,1.251382,2.048282,0.997338