In [1]:
import pandas as pd

df = pd.read_csv(r"D:\project\MindSense\Early_Detection\data\raw\student_data.csv.csv")

df.head()

,StudentID,Profile,Timestamp,Heart_Rate,Blood_Pressure_Systolic,Blood_Pressure_Diastolic,Respiration_Rate,Sleep_Duration,Activity_Levels,Mood,Cognitive_Load,Study_Hours,Academic_Stressors,Stress_Level,Mental_Health_Status
0,1,High_Achiever,1/1/2015,74.9,116.9,74.2,15.4,7.24,7019,Neutral,6,4.8,0,Medium,Normal
1,1,High_Achiever,1/2/2015,69.8,120.2,74,14.7,6.16,5411,Sad,5,6.59,0,Medium,Mild Stress
2,1,High_Achiever,1/3/2015,69.5,113.7,75.3,15.6,7.33,5627,Happy,5,4.67,1,Medium,Depression
3,1,High_Achiever,1/4/2015,70.8,114.6,79.4,15.2,7.22,5051,Happy,6,6.19,0,Medium,Depression
4,1,High_Achiever,1/5/2015,70.2,117.1,75.5,15.2,7.1,8066,Neutral,5,5.76,2,Medium,Depression

In [2]:
numeric_cols = [
    "Heart_Rate",
    "Blood_Pressure_Systolic",
    "Blood_Pressure_Diastolic",
    "Respiration_Rate",
    "Sleep_Duration",
    "Activity_Levels",
    "Cognitive_Load",
    "Study_Hours",
    "Academic_Stressors"
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 38651 entries, 0 to 38650
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   StudentID                 38651 non-null  str
 1   Profile                   38651 non-null  str
 2   Timestamp                 38651 non-null  str
 3   Heart_Rate                38650 non-null  float64
 4   Blood_Pressure_Systolic   38650 non-null  float64
 5   Blood_Pressure_Diastolic  38650 non-null  float64
 6   Respiration_Rate          38650 non-null  float64
 7   Sleep_Duration            38650 non-null  float64
 8   Activity_Levels           38650 non-null  float64
 9   Mood                      38651 non-null  str
 10  Cognitive_Load            38650 non-null  float64
 11  Study_Hours               38650 non-null  float64
 12  Academic_Stressors        38650 non-null  float64
 13  Stress_Level              38651 non-null  str
 14  Mental_Health_Status      38651 non-null  str
dtypes: float64(9), str(6)
memory usage: 4.4 MB

In [4]:
target = "Mental_Health_Status_encoded"

In [5]:
df["Mental_Health_Status"].value_counts()

Mental_Health_Status
Anxiety                 16679
Severe Stress            9302
Depression               5912
Moderate Stress          5849
Mild Stress               745
Normal                    163
Mental_Health_Status        1
Name: count, dtype: int64

In [6]:
df = df.sort_values(by=["StudentID", "Timestamp"])

In [7]:
df[df["StudentID"] == 1].head(10)

Empty DataFrame
Columns: [StudentID, Profile, Timestamp, Heart_Rate, Blood_Pressure_Systolic, Blood_Pressure_Diastolic, Respiration_Rate, Sleep_Duration, Activity_Levels, Mood, Cognitive_Load, Study_Hours, Academic_Stressors, Stress_Level, Mental_Health_Status]
Index: []

In [8]:
import pandas as pd

df = pd.read_csv(r"D:\project\MindSense\Early_Detection\data\raw\student_data.csv.csv")

df.head()

,StudentID,Profile,Timestamp,Heart_Rate,Blood_Pressure_Systolic,Blood_Pressure_Diastolic,Respiration_Rate,Sleep_Duration,Activity_Levels,Mood,Cognitive_Load,Study_Hours,Academic_Stressors,Stress_Level,Mental_Health_Status
0,1,High_Achiever,1/1/2015,74.9,116.9,74.2,15.4,7.24,7019,Neutral,6,4.8,0,Medium,Normal
1,1,High_Achiever,1/2/2015,69.8,120.2,74,14.7,6.16,5411,Sad,5,6.59,0,Medium,Mild Stress
2,1,High_Achiever,1/3/2015,69.5,113.7,75.3,15.6,7.33,5627,Happy,5,4.67,1,Medium,Depression
3,1,High_Achiever,1/4/2015,70.8,114.6,79.4,15.2,7.22,5051,Happy,6,6.19,0,Medium,Depression
4,1,High_Achiever,1/5/2015,70.2,117.1,75.5,15.2,7.1,8066,Neutral,5,5.76,2,Medium,Depression

In [9]:
df.columns = df.columns.str.strip()
df.columns

Index(['StudentID', 'Profile', 'Timestamp', 'Heart_Rate',
       'Blood_Pressure_Systolic', 'Blood_Pressure_Diastolic',
       'Respiration_Rate', 'Sleep_Duration', 'Activity_Levels', 'Mood',
       'Cognitive_Load', 'Study_Hours', 'Academic_Stressors', 'Stress_Level',
       'Mental_Health_Status'],
      dtype='str')

In [10]:
df.head(10)

,StudentID,Profile,Timestamp,Heart_Rate,Blood_Pressure_Systolic,Blood_Pressure_Diastolic,Respiration_Rate,Sleep_Duration,Activity_Levels,Mood,Cognitive_Load,Study_Hours,Academic_Stressors,Stress_Level,Mental_Health_Status
0,1,High_Achiever,1/1/2015,74.9,116.9,74.2,15.4,7.24,7019,Neutral,6,4.8,0,Medium,Normal
1,1,High_Achiever,1/2/2015,69.8,120.2,74,14.7,6.16,5411,Sad,5,6.59,0,Medium,Mild Stress
2,1,High_Achiever,1/3/2015,69.5,113.7,75.3,15.6,7.33,5627,Happy,5,4.67,1,Medium,Depression
3,1,High_Achiever,1/4/2015,70.8,114.6,79.4,15.2,7.22,5051,Happy,6,6.19,0,Medium,Depression
4,1,High_Achiever,1/5/2015,70.2,117.1,75.5,15.2,7.1,8066,Neutral,5,5.76,2,Medium,Depression
5,1,High_Achiever,1/6/2015,70.7,114,74.7,14.8,6.72,6450,Sad,6,4.61,1,Medium,Depression
6,1,High_Achiever,1/7/2015,69.7,117.4,77.6,15.7,6.14,6219,Anxious,5,4.86,0,Low,Depression
7,1,High_Achiever,1/8/2015,71.3,122,74.3,16.1,6.66,6822,Sad,6,5.49,0,Medium,Depression
8,1,High_Achiever,1/9/2015,70.6,122.3,77.4,16.4,6.57,5559,Sad,5,4.31,1,Medium,Depression
9,1,High_Achiever,1/10/2015,73.2,115.6,82,15.8,7.31,6774,Happy,6,5.48,1,Medium,Depression

In [11]:
df[df["Timestamp"] == "Timestamp"]

,StudentID,Profile,Timestamp,Heart_Rate,Blood_Pressure_Systolic,Blood_Pressure_Diastolic,Respiration_Rate,Sleep_Duration,Activity_Levels,Mood,Cognitive_Load,Study_Hours,Academic_Stressors,Stress_Level,Mental_Health_Status
38650,StudentID,Profile,Timestamp,Heart_Rate,Blood_Pressure_Systolic,Blood_Pressure_Diastolic,Respiration_Rate,Sleep_Duration,Activity_Levels,Mood,Cognitive_Load,Study_Hours,Academic_Stressors,Stress_Level,Mental_Health_Status

In [12]:
df["Timestamp"].tail(10)

38641    7/23/2025
38642    7/24/2025
38643    7/25/2025
38644    7/26/2025
38645    7/27/2025
38646    7/28/2025
38647    7/29/2025
38648    7/30/2025
38649    7/31/2025
38650    Timestamp
Name: Timestamp, dtype: str

In [13]:
invalid_dates = pd.to_datetime(df["Timestamp"], errors="coerce")

print(invalid_dates.isna().sum())

1

In [14]:
df[invalid_dates.isna()]

,StudentID,Profile,Timestamp,Heart_Rate,Blood_Pressure_Systolic,Blood_Pressure_Diastolic,Respiration_Rate,Sleep_Duration,Activity_Levels,Mood,Cognitive_Load,Study_Hours,Academic_Stressors,Stress_Level,Mental_Health_Status
38650,StudentID,Profile,Timestamp,Heart_Rate,Blood_Pressure_Systolic,Blood_Pressure_Diastolic,Respiration_Rate,Sleep_Duration,Activity_Levels,Mood,Cognitive_Load,Study_Hours,Academic_Stressors,Stress_Level,Mental_Health_Status

In [15]:
df = df[df["Timestamp"] != "Timestamp"]

df.shape

(38650, 15)

In [16]:
df["Timestamp"] = pd.to_datetime(df["Timestamp"])

In [17]:
df["Timestamp"].head()

0   2015-01-01
1   2015-01-02
2   2015-01-03
3   2015-01-04
4   2015-01-05
Name: Timestamp, dtype: datetime64[us]

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 38650 entries, 0 to 38649
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   StudentID                 38650 non-null  str
 1   Profile                   38650 non-null  str
 2   Timestamp                 38650 non-null  datetime64[us]
 3   Heart_Rate                38650 non-null  str
 4   Blood_Pressure_Systolic   38650 non-null  str
 5   Blood_Pressure_Diastolic  38650 non-null  str
 6   Respiration_Rate          38650 non-null  str
 7   Sleep_Duration            38650 non-null  str
 8   Activity_Levels           38650 non-null  str
 9   Mood                      38650 non-null  str
 10  Cognitive_Load            38650 non-null  str
 11  Study_Hours               38650 non-null  str
 12  Academic_Stressors        38650 non-null  str
 13  Stress_Level              38650 non-null  str
 14  Mental_Health_Status      38650 non-null  str
dtypes: datetime64[us](1), str(14)
memory usage: 4.4 MB

In [19]:
df = df.sort_values(by=["StudentID", "Timestamp"])

df.head()

,StudentID,Profile,Timestamp,Heart_Rate,Blood_Pressure_Systolic,Blood_Pressure_Diastolic,Respiration_Rate,Sleep_Duration,Activity_Levels,Mood,Cognitive_Load,Study_Hours,Academic_Stressors,Stress_Level,Mental_Health_Status
0,1,High_Achiever,2015-01-01,74.9,116.9,74.2,15.4,7.24,7019,Neutral,6,4.8,0,Medium,Normal
1,1,High_Achiever,2015-01-02,69.8,120.2,74,14.7,6.16,5411,Sad,5,6.59,0,Medium,Mild Stress
2,1,High_Achiever,2015-01-03,69.5,113.7,75.3,15.6,7.33,5627,Happy,5,4.67,1,Medium,Depression
3,1,High_Achiever,2015-01-04,70.8,114.6,79.4,15.2,7.22,5051,Happy,6,6.19,0,Medium,Depression
4,1,High_Achiever,2015-01-05,70.2,117.1,75.5,15.2,7.1,8066,Neutral,5,5.76,2,Medium,Depression

In [20]:
df.isnull().sum()

StudentID                   0
Profile                     0
Timestamp                   0
Heart_Rate                  0
Blood_Pressure_Systolic     0
Blood_Pressure_Diastolic    0
Respiration_Rate            0
Sleep_Duration              0
Activity_Levels             0
Mood                        0
Cognitive_Load              0
Study_Hours                 0
Academic_Stressors          0
Stress_Level                0
Mental_Health_Status        0
dtype: int64

In [21]:
numeric_columns = [
    "Heart_Rate",
    "Blood_Pressure_Systolic",
    "Blood_Pressure_Diastolic",
    "Respiration_Rate",
    "Sleep_Duration",
    "Activity_Levels",
    "Cognitive_Load",
    "Study_Hours",
    "Academic_Stressors"
]

for col in numeric_columns:
    df[col] = pd.to_numeric(df[col])

In [22]:
df.info()

<class 'pandas.DataFrame'>
Index: 38650 entries, 0 to 34784
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   StudentID                 38650 non-null  str
 1   Profile                   38650 non-null  str
 2   Timestamp                 38650 non-null  datetime64[us]
 3   Heart_Rate                38650 non-null  float64
 4   Blood_Pressure_Systolic   38650 non-null  float64
 5   Blood_Pressure_Diastolic  38650 non-null  float64
 6   Respiration_Rate          38650 non-null  float64
 7   Sleep_Duration            38650 non-null  float64
 8   Activity_Levels           38650 non-null  int64
 9   Mood                      38650 non-null  str
 10  Cognitive_Load            38650 non-null  int64
 11  Study_Hours               38650 non-null  float64
 12  Academic_Stressors        38650 non-null  int64
 13  Stress_Level              38650 non-null  str
 14  Mental_Health_Status      38650 non-null  str
dtypes: datetime64[us](1), float64(6), int64(3), str(5)
memory usage: 4.7 MB

In [23]:
df = df.sort_values(["StudentID", "Timestamp"])

df.head()

,StudentID,Profile,Timestamp,Heart_Rate,Blood_Pressure_Systolic,Blood_Pressure_Diastolic,Respiration_Rate,Sleep_Duration,Activity_Levels,Mood,Cognitive_Load,Study_Hours,Academic_Stressors,Stress_Level,Mental_Health_Status
0,1,High_Achiever,2015-01-01,74.9,116.9,74.2,15.4,7.24,7019,Neutral,6,4.80,0,Medium,Normal
1,1,High_Achiever,2015-01-02,69.8,120.2,74.0,14.7,6.16,5411,Sad,5,6.59,0,Medium,Mild Stress
2,1,High_Achiever,2015-01-03,69.5,113.7,75.3,15.6,7.33,5627,Happy,5,4.67,1,Medium,Depression
3,1,High_Achiever,2015-01-04,70.8,114.6,79.4,15.2,7.22,5051,Happy,6,6.19,0,Medium,Depression
4,1,High_Achiever,2015-01-05,70.2,117.1,75.5,15.2,7.10,8066,Neutral,5,5.76,2,Medium,Depression

In [24]:
print("Number of Students:", df["StudentID"].nunique())

Number of Students: 10

In [25]:
df["Mood"].value_counts()

Mood
Anxious    14198
Sad        11242
Neutral    10163
Happy       3047
Name: count, dtype: int64

In [26]:
df["Stress_Level"].value_counts()

Stress_Level
High      20095
Medium    18421
Low         134
Name: count, dtype: int64

In [27]:
df["Mental_Health_Status"].value_counts()

Mental_Health_Status
Anxiety            16679
Severe Stress       9302
Depression          5912
Moderate Stress     5849
Mild Stress          745
Normal               163
Name: count, dtype: int64

In [28]:
from sklearn.preprocessing import LabelEncoder

In [29]:
mood_encoder = LabelEncoder()
stress_encoder = LabelEncoder()
mental_encoder = LabelEncoder()

In [30]:
df["Mood"] = mood_encoder.fit_transform(df["Mood"])

df["Stress_Level"] = stress_encoder.fit_transform(df["Stress_Level"])

df["Mental_Health_Status"] = mental_encoder.fit_transform(df["Mental_Health_Status"])

In [31]:
df.head()

,StudentID,Profile,Timestamp,Heart_Rate,Blood_Pressure_Systolic,Blood_Pressure_Diastolic,Respiration_Rate,Sleep_Duration,Activity_Levels,Mood,Cognitive_Load,Study_Hours,Academic_Stressors,Stress_Level,Mental_Health_Status
0,1,High_Achiever,2015-01-01,74.9,116.9,74.2,15.4,7.24,7019,2,6,4.80,0,2,4
1,1,High_Achiever,2015-01-02,69.8,120.2,74.0,14.7,6.16,5411,3,5,6.59,0,2,2
2,1,High_Achiever,2015-01-03,69.5,113.7,75.3,15.6,7.33,5627,1,5,4.67,1,2,1
3,1,High_Achiever,2015-01-04,70.8,114.6,79.4,15.2,7.22,5051,1,6,6.19,0,2,1
4,1,High_Achiever,2015-01-05,70.2,117.1,75.5,15.2,7.10,8066,2,5,5.76,2,2,1

In [32]:
print("Mood Classes:")
print(mood_encoder.classes_)

Mood Classes:
['Anxious' 'Happy' 'Neutral' 'Sad']

In [33]:
print("Stress Classes:")
print(stress_encoder.classes_)

Stress Classes:
['High' 'Low' 'Medium']

In [34]:
print("Mental Health Classes:")
print(mental_encoder.classes_)

Mental Health Classes:
['Anxiety' 'Depression' 'Mild Stress' 'Moderate Stress' 'Normal'
 'Severe Stress']

In [35]:
df.to_csv(
"D:/project/MindSense/Early_Detection/data/processed/cleaned_student_data.csv",
index=False
)

In [36]:
import os

os.listdir("D:/project/MindSense/Early_Detection/data/processed")

['cleaned_student_data.csv',
 'X_test.npy',
 'X_train.npy',
 'X_val.npy',
 'y_test.npy',
 'y_train.npy',
 'y_val.npy']

In [37]:
clean_df = pd.read_csv(
    "D:/project/MindSense/Early_Detection/data/processed/cleaned_student_data.csv"
)

clean_df.head()

,StudentID,Profile,Timestamp,Heart_Rate,Blood_Pressure_Systolic,Blood_Pressure_Diastolic,Respiration_Rate,Sleep_Duration,Activity_Levels,Mood,Cognitive_Load,Study_Hours,Academic_Stressors,Stress_Level,Mental_Health_Status
0,1,High_Achiever,2015-01-01,74.9,116.9,74.2,15.4,7.24,7019,2,6,4.80,0,2,4
1,1,High_Achiever,2015-01-02,69.8,120.2,74.0,14.7,6.16,5411,3,5,6.59,0,2,2
2,1,High_Achiever,2015-01-03,69.5,113.7,75.3,15.6,7.33,5627,1,5,4.67,1,2,1
3,1,High_Achiever,2015-01-04,70.8,114.6,79.4,15.2,7.22,5051,1,6,6.19,0,2,1
4,1,High_Achiever,2015-01-05,70.2,117.1,75.5,15.2,7.10,8066,2,5,5.76,2,2,1

In [38]:
os.listdir("D:/project/MindSense/Early_Detection/data/processed")

['cleaned_student_data.csv',
 'X_test.npy',
 'X_train.npy',
 'X_val.npy',
 'y_test.npy',
 'y_train.npy',
 'y_val.npy']